name: All Packers Expeditions Email Campaign

on:
  # Runs once a week on Mondays at 6:00 AM UTC
  schedule:
    - cron: "0 6 * * 1"
  # Allows manual trigger in GitHub Actions UI
  workflow_dispatch:

jobs:
  send_emails:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Check out repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv

      # Step 4: Run the script
      - name: Run allpackersNotification.py
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        run: |
          python allpackersNotification.py
